### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by anantshri** [k3170makan/DroidSploit#1]
What's the license on this script.

Is it okey if we include some of these stuff into https://github.com/AndroidTamer/drozer_checks.

Please suggest if this would be allowed. I am opening an issue on the other side also to keep a track on this. Once we get your approval only then we will try to integrate those features in and as always credit will be provided where credit is due.

**Comment by k3170makan** [comment]
Go for it man! I have no problem with you  guys using my stuff ;)

Keith Makan
"i fight for the users"
https://about.me/k3170makan

On 09 Feb 2017 08:37, "Anant Shrivastava" <notifications@github.com> wrote:

What's the license on this script.

Is it okey if we include some of these stuff into https://github.com/
AndroidTamer/drozer_checks.

Please suggest if this would be allowed. I am opening an issue on the other
side also to keep a track on this. Once we get your approval only then we
will try to integrate those features in and as always credit will be
provided where credit is due.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/k3170makan/DroidSploit/issues/1>, or mute the thread

**Comment by anantshri** [comment]
Awesome. Thanks for the good work.
